### ISSUE TITLE
用生成数据pretrain的网络在test时 scale和translation误差很大

### ISSUE THREAD

**Issue by lvZic** [yueyang130/3D-Hand-Shape-and-Pose-from-Images-in-the-Wild-#2]
感谢你的复现工作，我发现scale和tans loss无法下降， 预训练完成后还是几千的loss，test时效果也很差，请问会是哪里的问题呢？

**Comment by txytju** [comment]
> 感谢你的复现工作，我发现scale和tans loss无法下降， 预训练完成后还是几千的loss，test时效果也很差，请问会是哪里的问题呢？

我也遇到了同样的问题，请问有解决吗

**Comment by lvZic** [comment]
> > 感谢你的复现工作，我发现scale和tans loss无法下降， 预训练完成后还是几千的loss，test时效果也很差，请问会是哪里的问题呢？
> 
> 我也遇到了同样的问题，请问有解决吗

我认为相机参数无法用于direct loss 只能通过3D， 2D loss来隐含学习
